version: '3.8'

services:
    server:
        container_name: server
        build: .
        depends_on:
            - postgres
        ports:
            - '8000:8000'
        volumes:
            - .:/usr/app
        env_file: .env
        command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

    postgres:
        container_name: postgres
        image: postgres:alpine
        environment:
            POSTGRES_DB: users
            POSTGRES_USER: toor
            POSTGRES_PASSWORD: root
        ports:
            - '5432:5432'
